// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCwMXGCOf860PhbTnX_HceVcRaEtZvFAYc',
    appId: '1:543640605365:web:742f43cd30c1ca4bc724fc',
    messagingSenderId: '543640605365',
    projectId: 'face-recog-attendance-007',
    authDomain: 'face-recog-attendance-007.firebaseapp.com',
    storageBucket: 'face-recog-attendance-007.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCTh2HS_0Ykt4wrfczGEYnQjTREhNaU1mk',
    appId: '1:543640605365:android:28fc2f454e07d303c724fc',
    messagingSenderId: '543640605365',
    projectId: 'face-recog-attendance-007',
    storageBucket: 'face-recog-attendance-007.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC7Sed8lYkuxk_RprlCjgAwNfUfBIjv3fM',
    appId: '1:543640605365:ios:6224db9a51a1351ec724fc',
    messagingSenderId: '543640605365',
    projectId: 'face-recog-attendance-007',
    storageBucket: 'face-recog-attendance-007.appspot.com',
    iosClientId: '543640605365-gi7cobfdl50bbam8sn2a1h4g5rsem2ct.apps.googleusercontent.com',
    iosBundleId: 'com.example.nmitHackCodeInvaders',
  );
}
